import {
  ArrowUp,
  ArrowsOut,
  Barbell,
  Bathtub,
  Bed,
  Bell,
  Building,
  Calendar,
  CalendarCheck,
  CaretLeft,
  CaretRight,
  CarSimple,
  ChartBar,
  ChatCircle,
  Check,
  CheckCircle,
  Coffee,
  Compass,
  CookingPot,
  FireExtinguisher,
  FunnelSimple,
  GlobeSimple,
  GridFour,
  Heart,
  House,
  ImageSquare,
  Key,
  Lifebuoy,
  List,
  MagnifyingGlass,
  MapPin,
  MapTrifold,
  Minus,
  PawPrint,
  PencilSimple,
  PlayCircle,
  Plus,
  Rows,
  ShieldCheck,
  Snowflake,
  Sparkle,
  Star,
  Suitcase,
  Television,
  Thermometer,
  Trash,
  User,
  UsersThree,
  VideoCamera,
  Wallet,
  Warning,
  WashingMachine,
  Waves,
  WifiHigh,
  X,
  XCircle,
} from "@phosphor-icons/react/ssr";

import type { Icon as PhosphorIcon } from "@phosphor-icons/react";

export const ICON_REGISTRY = {
  arrowUp: ArrowUp,
  search: MagnifyingGlass,
  heart: Heart,
  heartFilled: Heart, 
  menu: List,
  globe: GlobeSimple,
  filter: FunnelSimple,
  star: Star,
  mapPin: MapPin,
  calendar: Calendar,
  calendarCheck: CalendarCheck,
  user: User,
  close: X,
  chevronLeft: CaretLeft,
  chevronRight: CaretRight,
  sparkle: Sparkle,
  bell: Bell,
  house: House,
  building: Building,
  shieldCheck: ShieldCheck,
  suitcase: Suitcase,
  chatCircle: ChatCircle,
  lifebuoy: Lifebuoy,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  warning: Warning,
  chartBar: ChartBar,
  minus: Minus,
  plus: Plus,
  compass: Compass,
  // Property discovery (prompt 20).
  image: ImageSquare,
  playCircle: PlayCircle,
  bed: Bed,
  bathtub: Bathtub,
  guests: UsersThree,
  mapView: MapTrifold,
  listView: Rows,
  expand: ArrowsOut,
  gridFour: GridFour,
  wifi: WifiHigh,
  pool: Waves,
  kitchen: CookingPot,
  ac: Snowflake,
  parking: CarSimple,
  tv: Television,
  washer: WashingMachine,
  heating: Thermometer,
  selfCheckIn: Key,
  petFriendly: PawPrint,
  gym: Barbell,
  securityCamera: VideoCamera,
  safetyAlarm: FireExtinguisher,
  breakfast: Coffee,
  wallet: Wallet,
  pencil: PencilSimple,
  trash: Trash,
  check: Check,
} satisfies Record<string, PhosphorIcon>;

export type IconName = keyof typeof ICON_REGISTRY;
